### ISSUE TITLE
/system/bin/sh: cat: /proc/kmsg: Permission denied

### ISSUE THREAD

**Issue by tenpn** [youngker/elogcat.el#2]
I'm getting the above error when calling `elogcat`. Or rather, the elogcat buffer is created and that text is the only contents. I've got (among others) Android 6 SDK installed, and platform tools 23.0.1. I've got elogcat 20151120 installed from melpa. 

I've currently got a device attached, I can see logcat output in android studio, and `adb devices` lists my device.

**Comment by youngker** [comment]
Hi tenpn 
you can't to get kernel logs on unrooted device.
you should add these line in your init file.

(require 'elogcat)
(setq elogcat-enable-klog nil)

Thanks.

**Comment by tenpn** [comment]
thanks!
